Diary = ->
  that = this
  return
  
Diary::setup = (callback) ->
  #First, setup the database
  @db = window.openDatabase('diary', 1, 'diary', 1000000)
  @db.transaction @initDB, @dbErrorHandler, callback
  return

#Geenric database error handler. Won't do anything for now.

Diary::dbErrorHandler = (e) ->
  console.log 'DB Error'
  console.dir e
  return

#I initialize the database structure

Diary::initDB = (t) ->
  t.executeSql 'create table if not exists diary(id INTEGER PRIMARY KEY AUTOINCREMENT, title TEXT, body TEXT, image TEXT, published DATE)'
  return

Diary::getEntries = (start, callback) ->
  console.log 'Running getEntries'
  if arguments.length == 1
    callback = arguments[0]
  @db.transaction ((t) ->
    t.executeSql 'select id, title, body, image, published from diary order by published desc', [], ((t, results) ->
      callback that.fixResults(results)
      return
    ), @dbErrorHandler
    return
  ), @dbErrorHandler
  return

Diary::getEntry = (id, callback) ->
  @db.transaction ((t) ->
    t.executeSql 'select id, title, body, image, published from diary where id = ?', [ id ], ((t, results) ->
      callback that.fixResult(results)
      return
    ), @dbErrorHandler
    return
  ), @dbErrorHandler
  return

#No support for edits yet

Diary::saveEntry = (data, callback) ->
  console.dir data
  @db.transaction ((t) ->
    t.executeSql 'insert into diary(title,body,image,published) values(?,?,?,?)', [
      data.title
      data.body
      data.image
      (new Date).getTime()
    ], (->
      callback()
      return
    ), @dbErrorHandler
    return
  ), @dbErrorHandler
  return

#Utility to convert record sets into array of obs

Diary::fixResults = (res) ->
  result = []
  i = 0
  len = res.rows.length
  while i < len
    row = res.rows.item(i)
    result.push row
    i++
  result

#I'm a lot like fixResults, but I'm only used in the context of expecting one row, so I return an ob, not an array

Diary::fixResult = (res) ->
  if res.rows.length
    res.rows.item 0
  else
    {}

# ---
# generated by js2coffee 2.2.0