diary = undefined
mainView = undefined

deviceready = ->
  console.log 'deviceready'
  #create a new instance of our Diary and listen for it to complete it's setup
  diary = new Diary
  diary.setup startApp
  return

###
Main application handler. At this point my database is setup and I can start listening for events.
###

startApp = ->
  console.log 'startApp'
  mainView = $('#mainView')
  #Load the main view
  pageLoad 'main.html'
  #Always listen for home click
  $(document).on 'touchend', '.homeButton', (e) ->
    e.preventDefault()
    pageLoad 'main.html'
    return
  return

pageLoad = (u) ->
  console.log 'load ' + u
  #convert url params into an ob
  data = {}
  if u.indexOf('?') >= 0
    qs = u.split('?')[1]
    parts = qs.split('&')
    i = 0
    len = parts.length
    while i < len
      bits = parts[i].split('=')
      data[bits[0]] = bits[1]
      i++
  $.get u, (res, code) ->
    mainView.html res
    evt = document.createEvent('CustomEvent')
    evt.initCustomEvent 'pageload', true, true, data
    page = $('div', mainView)
    page[0].dispatchEvent evt
    return
  return

document.addEventListener 'deviceready', deviceready, false
$(document).on 'pageload', '#mainPage', (e) ->
  diary.getEntries (data) ->
    console.log 'getEntries'
    s = ''
    i = 0
    len = data.length
    while i < len
      s += '<div data-id=\'' + data[i].id + '\'>' + data[i].title + '</div>'
      i++
    $('#entryList').html s
    #Listen for add clicks
    $('#addEntryBtn').on 'touchstart', (e) ->
      e.preventDefault()
      pageLoad 'add.html'
      return
    #Listen for entry clicks
    $('#entryList div').on 'touchstart', (e) ->
      e.preventDefault()
      console.log 'entry click'
      id = $(this).data('id')
      pageLoad 'entry.html?id=' + id
      return
    return
  return
$(document).on 'pageload', '#entryPage', (e) ->
  diary.getEntry Number(e.detail.id), (ob) ->
    content = '<h2>' + ob.title + '</h2>'
    #content += "Written "+dtFormat(ob.published) + "<br/><br/>";
    content += ob.body
    if ob.image
      content += '<img class=\'imgDisplay\' src=\'' + ob.image + '\'>'
    console.log ob.image
    $('#entryDisplay').html content
    return
  return
$(document).on 'pageload', '#addPage', (e) ->

  onCamSuccess = (imgdata) ->
    console.log imgdata
    $('#entryPicture').val imgdata
    $('#imgPreview').attr 'src', imgdata
    return

  onCamFail = (e) ->
    console.log 'camFail'
    console.dir e
    navigator.notification.alert 'Sorry, something went wrong.', null, 'Oops!'
    return

  $('#takePicture').on 'touchstart', (e) ->
    e.preventDefault()
    navigator.camera.getPicture onCamSuccess, onCamFail,
      quality: 50
      destinationType: Camera.DestinationType.FILE_URI
    return
  $('#addEntrySubmit').on 'touchstart', (e) ->
    e.preventDefault()
    #grab the values
    title = $('#entryTitle').val()
    body = $('#entryBody').val()
    img = $('#entryPicture').val()
    #store!
    diary.saveEntry {
      title: title
      body: body
      image: img
    }, ->
      pageLoad 'main.html'
      return
    return
  return

# ---
# generated by js2coffee 2.2.0